[package]
name = "executable-finder"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Find executables in PATH variable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
